apiVersion: v1
kind: Service
metadata:
  name: fjordline-booking-service
spec:
  selector:
    app: fjordline-booking
  ports:
    - protocol: TCP
      port: 80         # The port the service listens on
      targetPort: 3000 # The port the Express app listens on
  type: LoadBalancer   # Creates a public IP for access